import { useState } from "react";

const sampleRequests = [
  "Add a dark mode toggle to a React dashboard and persist selected theme across refreshes",
  "Add search and status filtering to a task management dashboard",
  "Add client-side validation to a signup form with helpful error messages",
  "Add export-to-CSV functionality for a reports table"
];

const stageStyles = {
  planning: "bg-blue-500/15 text-blue-200 border-blue-400/30",
  implementation: "bg-purple-500/15 text-purple-200 border-purple-400/30",
  testing: "bg-amber-500/15 text-amber-200 border-amber-400/30",
  review: "bg-emerald-500/15 text-emerald-200 border-emerald-400/30",
  revision: "bg-orange-500/15 text-orange-200 border-orange-400/30",
  documentation: "bg-pink-500/15 text-pink-200 border-pink-400/30",
  start: "bg-slate-500/15 text-slate-200 border-slate-400/30",
  completed: "bg-green-500/15 text-green-200 border-green-400/30"
};

function downloadMarkdownFile(filename, content) {
  const blob = new Blob([content], {
    type: "text/markdown;charset=utf-8"
  });

  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();

  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function buildPrPackageMarkdown(workflow) {
  const finalPackage = workflow.finalPackage || {};

  const agentSections = (workflow.agents || [])
    .map((agent, index) => {
      return `## ${index + 1}. ${agent.agent}

**Stage:** ${agent.stage}  
**Status:** ${agent.status}  
**Provider:** ${agent.provider}  

### Summary

${agent.summary}

### Output

\`\`\`json
${JSON.stringify(agent.output, null, 2)}
\`\`\`
`;
    })
    .join("\n");

  const bandTimeline = (workflow.bandMessages || [])
    .map((message, index) => {
      return `${index + 1}. **${message.agent}** [${message.stage}] - ${message.message}`;
    })
    .join("\n");

  return `# DevBand PR Delivery Package

## Feature Request

${workflow.featureRequest}

## Workflow Details

- **Workflow ID:** ${workflow.workflowId}
- **Status:** ${workflow.status}
- **Band Room:** ${workflow.bandRoom?.roomName || "N/A"}
- **Band Room ID:** ${workflow.bandRoom?.roomId || "N/A"}
- **Band Mode:** ${workflow.bandRoom?.mode || "N/A"}

## Final PR Package

### PR Title

${finalPackage.prTitle || "N/A"}

### PR Summary

${finalPackage.prSummary || "N/A"}

### Final Status

${finalPackage.finalStatus || "N/A"}

## Release Notes

${(finalPackage.releaseNotes || []).map((item) => `- ${item}`).join("\n")}

## Developer Notes

${(finalPackage.developerNotes || []).map((item) => `- ${item}`).join("\n")}

## README Update

${finalPackage.readmeUpdate || "N/A"}

## Agent Outputs

${agentSections}

## Band Collaboration Timeline

${bandTimeline}

---

Generated by DevBand: Band-Powered Multi-Agent Software Delivery Team.
`;
}

function JsonBlock({ data }) {
  return (
    <pre className="mt-4 max-h-96 overflow-auto rounded-2xl border border-slate-700 bg-slate-950/80 p-4 text-xs leading-relaxed text-slate-200">
      {JSON.stringify(data, null, 2)}
    </pre>
  );
}

function StatusPill({ children, className = "" }) {
  return (
    <span
      className={`inline-flex items-center rounded-full border px-3 py-1 text-xs font-medium ${className}`}
    >
      {children}
    </span>
  );
}

function AgentCard({ agent, index }) {
  const style =
    stageStyles[agent.stage] ||
    "bg-slate-500/15 text-slate-200 border-slate-400/30";

  return (
    <div className="rounded-3xl border border-slate-800 bg-slate-900/70 p-5 shadow-xl shadow-slate-950/30">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <div className="flex items-center gap-3">
            <div className="flex h-9 w-9 items-center justify-center rounded-2xl bg-cyan-400 text-sm font-bold text-slate-950">
              {index + 1}
            </div>
            <div>
              <h3 className="text-lg font-semibold text-white">{agent.agent}</h3>
              <p className="text-sm text-slate-400">{agent.summary}</p>
            </div>
          </div>
        </div>

        <div className="flex flex-wrap gap-2">
          <StatusPill className={style}>{agent.stage}</StatusPill>
          <StatusPill className="border-green-400/30 bg-green-500/15 text-green-200">
            {agent.status}
          </StatusPill>
          <StatusPill className="border-cyan-400/30 bg-cyan-500/15 text-cyan-200">
            {agent.provider}
          </StatusPill>
        </div>
      </div>

      <JsonBlock data={agent.output} />
    </div>
  );
}

function BandMessageCard({ message, index }) {
  const style =
    stageStyles[message.stage] ||
    "bg-slate-500/15 text-slate-200 border-slate-400/30";

  return (
    <div className="relative rounded-2xl border border-slate-800 bg-slate-950/50 p-4">
      <div className="absolute -left-3 top-5 flex h-6 w-6 items-center justify-center rounded-full bg-cyan-400 text-xs font-bold text-slate-950">
        {index + 1}
      </div>

      <div className="ml-2 flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
        <div>
          <p className="font-semibold text-white">{message.agent}</p>
          <p className="mt-1 text-sm text-slate-300">{message.message}</p>
          <p className="mt-2 text-xs text-slate-500">{message.createdAt}</p>
        </div>

        <StatusPill className={style}>{message.stage}</StatusPill>
      </div>
    </div>
  );
}

function WorkflowMetrics({ workflow }) {
  if (!workflow) return null;

  const totalAgents = workflow.agents?.length || 0;
  const totalBandMessages = workflow.bandMessages?.length || 0;
  const hasRevisionLoop = workflow.agents?.some(
    (agent) => agent.stage === "revision"
  );

  const reviewAgent = workflow.agents?.find(
    (agent) => agent.stage === "review"
  );

  const finalStatus = workflow.finalPackage?.finalStatus || workflow.status;

  const metrics = [
    {
      label: "Agents Collaborated",
      value: totalAgents,
      description: "Specialized agents participated in the workflow",
      accent: "text-cyan-300"
    },
    {
      label: "Band Messages",
      value: totalBandMessages,
      description: "Structured collaboration events exchanged",
      accent: "text-purple-300"
    },
    {
      label: "Review Loop",
      value: hasRevisionLoop ? "Completed" : "Skipped",
      description: hasRevisionLoop
        ? "Reviewer feedback triggered engineering revision"
        : "No revision was required",
      accent: hasRevisionLoop ? "text-orange-300" : "text-slate-300"
    },
    {
      label: "Review Status",
      value: reviewAgent?.output?.reviewStatus || "N/A",
      description: "Code review decision from reviewer agent",
      accent: "text-emerald-300"
    },
    {
      label: "Final Status",
      value: finalStatus,
      description: "Delivery package readiness state",
      accent: "text-green-300"
    }
  ];

  return (
    <section className="rounded-[2rem] border border-slate-800 bg-slate-950/70 p-6 shadow-xl shadow-black/20 backdrop-blur md:p-8">
      <div className="mb-6">
        <p className="text-sm font-semibold uppercase tracking-[0.25em] text-slate-400">
          Workflow Summary
        </p>
        <h2 className="mt-2 text-2xl font-bold text-white">
          Multi-Agent Collaboration Metrics
        </h2>
      </div>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">
        {metrics.map((metric) => (
          <div
            key={metric.label}
            className="rounded-3xl border border-slate-800 bg-slate-900/70 p-5"
          >
            <p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">
              {metric.label}
            </p>
            <p className={`mt-3 text-2xl font-black ${metric.accent}`}>
              {metric.value}
            </p>
            <p className="mt-2 text-xs leading-5 text-slate-400">
              {metric.description}
            </p>
          </div>
        ))}
      </div>
    </section>
  );
}

function BandUsageExplanation() {
  const bandPoints = [
    {
      title: "Shared Collaboration Room",
      description:
        "DevBand creates a dedicated Band-style room for every software delivery workflow so all agents can coordinate around the same feature request."
    },
    {
      title: "Structured Context Handoffs",
      description:
        "Each agent posts structured JSON output into the collaboration timeline, allowing the next agent to continue with full context instead of starting from scratch."
    },
    {
      title: "Visible Agent-to-Agent Messages",
      description:
        "Planner, Engineer, Tester, Reviewer, Revision, and Documentation agents all publish messages that make the collaboration trail easy to inspect."
    },
    {
      title: "Review-Driven Decision Loop",
      description:
        "When the Code Reviewer Agent approves with suggestions, DevBand routes the task back to the Software Engineer Revision Agent before documentation."
    },
    {
      title: "Audit-Ready Delivery Trail",
      description:
        "The final PR package is backed by an ordered timeline of agent messages, decisions, outputs, and handoffs."
    }
  ];

  return (
    <section className="rounded-[2rem] border border-cyan-400/20 bg-cyan-950/10 p-6 shadow-xl shadow-black/20 backdrop-blur md:p-8">
      <div className="mb-6">
        <p className="text-sm font-semibold uppercase tracking-[0.25em] text-cyan-300">
          Band Coordination Layer
        </p>
        <h2 className="mt-2 text-2xl font-bold text-white">
          How DevBand Uses Band
        </h2>
        <p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">
          In the current MVP, DevBand runs in mock Band mode while preserving the
          same collaboration structure we will connect to the live Band platform:
          room creation, structured messages, agent handoffs, review decisions,
          and an audit-ready workflow timeline.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">
        {bandPoints.map((point, index) => (
          <div
            key={point.title}
            className="rounded-3xl border border-slate-800 bg-slate-950/60 p-5"
          >
            <div className="mb-4 flex h-9 w-9 items-center justify-center rounded-2xl bg-cyan-400 text-sm font-black text-slate-950">
              {index + 1}
            </div>
            <h3 className="text-sm font-bold text-white">{point.title}</h3>
            <p className="mt-3 text-xs leading-5 text-slate-400">
              {point.description}
            </p>
          </div>
        ))}
      </div>
    </section>
  );
}

function FinalPackage({ finalPackage, workflow }) {
  if (!finalPackage) return null;

  return (
    <section className="rounded-3xl border border-cyan-400/30 bg-cyan-950/20 p-6 shadow-2xl shadow-cyan-950/20">
      <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-sm font-semibold uppercase tracking-[0.3em] text-cyan-300">
            Final Delivery Package
          </p>
          <h2 className="mt-2 text-2xl font-bold text-white">
            PR Package Ready
          </h2>
        </div>

        <div className="flex flex-wrap gap-3">
          <StatusPill className="border-green-400/30 bg-green-500/15 text-green-200">
            {finalPackage.finalStatus || "ready"}
          </StatusPill>

          <button
            onClick={() =>
              downloadMarkdownFile(
                `devband-pr-package-${workflow.workflowId}.md`,
                buildPrPackageMarkdown(workflow)
              )
            }
            className="rounded-full border border-cyan-400/30 bg-cyan-500/15 px-4 py-1 text-xs font-semibold text-cyan-200 transition hover:bg-cyan-500/25"
          >
            Download PR Package
          </button>
        </div>
      </div>

      <div className="mt-6 grid gap-4 lg:grid-cols-2">
        <div className="rounded-2xl border border-slate-800 bg-slate-950/60 p-4">
          <p className="text-sm font-semibold text-slate-400">PR Title</p>
          <p className="mt-2 text-lg font-semibold text-white">
            {finalPackage.prTitle}
          </p>
        </div>

        <div className="rounded-2xl border border-slate-800 bg-slate-950/60 p-4">
          <p className="text-sm font-semibold text-slate-400">Status</p>
          <p className="mt-2 text-lg font-semibold text-green-300">
            {finalPackage.finalStatus}
          </p>
        </div>
      </div>

      <div className="mt-4 rounded-2xl border border-slate-800 bg-slate-950/60 p-4">
        <p className="text-sm font-semibold text-slate-400">PR Summary</p>
        <p className="mt-2 text-sm leading-6 text-slate-200">
          {finalPackage.prSummary}
        </p>
      </div>

      <div className="mt-4 grid gap-4 lg:grid-cols-2">
        <div className="rounded-2xl border border-slate-800 bg-slate-950/60 p-4">
          <p className="text-sm font-semibold text-slate-400">Release Notes</p>
          <ul className="mt-3 space-y-2 text-sm text-slate-200">
            {(finalPackage.releaseNotes || []).map((item, index) => (
              <li key={index}>• {item}</li>
            ))}
          </ul>
        </div>

        <div className="rounded-2xl border border-slate-800 bg-slate-950/60 p-4">
          <p className="text-sm font-semibold text-slate-400">Developer Notes</p>
          <ul className="mt-3 space-y-2 text-sm text-slate-200">
            {(finalPackage.developerNotes || []).map((item, index) => (
              <li key={index}>• {item}</li>
            ))}
          </ul>
        </div>
      </div>

      <div className="mt-4 rounded-2xl border border-slate-800 bg-slate-950/60 p-4">
        <p className="text-sm font-semibold text-slate-400">README Update</p>
        <pre className="mt-3 whitespace-pre-wrap text-sm leading-6 text-slate-200">
          {finalPackage.readmeUpdate}
        </pre>
      </div>
    </section>
  );
}

function App() {
  const [featureRequest, setFeatureRequest] = useState(sampleRequests[0]);
  const [workflow, setWorkflow] = useState(null);
  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState("");

  async function startWorkflow() {
    setLoading(true);
    setErrorMessage("");
    setWorkflow(null);

    try {
      const response = await fetch("/api/workflows/start", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ featureRequest })
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Workflow failed");
      }

      setWorkflow(data);
    } catch (error) {
      setErrorMessage(error.message);
    } finally {
      setLoading(false);
    }
  }

  return (
    <main className="min-h-screen bg-[radial-gradient(circle_at_top_left,#164e63,transparent_35%),linear-gradient(135deg,#020617,#0f172a_45%,#111827)] px-4 py-8 text-slate-100 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-7xl">
        <section className="rounded-[2rem] border border-slate-800 bg-slate-950/70 p-6 shadow-2xl shadow-black/30 backdrop-blur md:p-10">
          <div className="grid gap-8 lg:grid-cols-[1.1fr_0.9fr] lg:items-center">
            <div>
              <div className="inline-flex rounded-full border border-cyan-400/30 bg-cyan-500/10 px-4 py-2 text-sm font-medium text-cyan-200">
                Band of Agents Hackathon · Track 2
              </div>

              <h1 className="mt-6 text-4xl font-black tracking-tight text-white md:text-6xl">
                DevBand
              </h1>

              <p className="mt-4 max-w-2xl text-lg leading-8 text-slate-300">
                A Band-powered multi-agent software delivery team where planner,
                engineer, tester, reviewer, revision, and documentation agents collaborate
                to transform a feature request into a PR-ready delivery package.
              </p>

              <div className="mt-6 flex flex-wrap gap-3">
                <StatusPill className="border-cyan-400/30 bg-cyan-500/15 text-cyan-200">
                  6 agent steps
                </StatusPill>
                <StatusPill className="border-purple-400/30 bg-purple-500/15 text-purple-200">
                  Structured handoffs
                </StatusPill>
                <StatusPill className="border-orange-400/30 bg-orange-500/15 text-orange-200">
                  Review revision loop
                </StatusPill>
                <StatusPill className="border-green-400/30 bg-green-500/15 text-green-200">
                  Mock Band room enabled
                </StatusPill>
              </div>
            </div>

            <div className="rounded-3xl border border-slate-800 bg-slate-900/70 p-5">
              <p className="text-sm font-semibold uppercase tracking-[0.25em] text-slate-400">
                Agent Workflow
              </p>

              <div className="mt-5 space-y-3">
                {[
                  "Product Planner Agent",
                  "Software Engineer Agent",
                  "Test Engineer Agent",
                  "Code Reviewer Agent",
                  "Software Engineer Revision Agent",
                  "Documentation Agent"
                ].map((agent, index) => (
                  <div
                    key={agent}
                    className="flex items-center gap-3 rounded-2xl border border-slate-800 bg-slate-950/60 p-3"
                  >
                    <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-cyan-400 text-xs font-bold text-slate-950">
                      {index + 1}
                    </div>
                    <p className="text-sm font-medium text-slate-200">{agent}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        <section className="mt-8 rounded-[2rem] border border-slate-800 bg-slate-950/70 p-6 shadow-xl shadow-black/20 backdrop-blur md:p-8">
          <div className="grid gap-6 lg:grid-cols-[1fr_320px]">
            <div>
              <label className="text-sm font-semibold uppercase tracking-[0.25em] text-slate-400">
                Feature Request
              </label>

              <textarea
                value={featureRequest}
                onChange={(event) => setFeatureRequest(event.target.value)}
                rows={5}
                className="mt-3 w-full resize-none rounded-3xl border border-slate-700 bg-slate-900 p-5 text-base leading-7 text-white outline-none ring-cyan-400/30 transition focus:border-cyan-400 focus:ring-4"
                placeholder="Describe the software feature you want DevBand agents to deliver..."
              />

              {errorMessage && (
                <div className="mt-4 rounded-2xl border border-red-400/30 bg-red-500/10 p-4 text-sm text-red-200">
                  {errorMessage}
                </div>
              )}

              <button
                onClick={startWorkflow}
                disabled={loading || !featureRequest.trim()}
                className="mt-5 rounded-2xl bg-cyan-400 px-6 py-3 font-bold text-slate-950 shadow-lg shadow-cyan-950/30 transition hover:bg-cyan-300 disabled:cursor-not-allowed disabled:opacity-50"
              >
                {loading ? "Agents collaborating..." : "Start DevBand Workflow"}
              </button>
            </div>

            <div>
              <p className="text-sm font-semibold uppercase tracking-[0.25em] text-slate-400">
                Try Examples
              </p>

              <div className="mt-3 space-y-3">
                {sampleRequests.map((request) => (
                  <button
                    key={request}
                    onClick={() => setFeatureRequest(request)}
                    className="w-full rounded-2xl border border-slate-800 bg-slate-900/80 p-3 text-left text-sm leading-6 text-slate-300 transition hover:border-cyan-400/40 hover:bg-slate-800"
                  >
                    {request}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </section>

        {workflow && (
          <div className="mt-8 space-y-8">
            <WorkflowMetrics workflow={workflow} />

            <BandUsageExplanation />

            <section className="rounded-[2rem] border border-slate-800 bg-slate-950/70 p-6 shadow-xl shadow-black/20 backdrop-blur md:p-8">
              <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
                <div>
                  <p className="text-sm font-semibold uppercase tracking-[0.25em] text-slate-400">
                    Band Collaboration Room
                  </p>
                  <h2 className="mt-2 text-2xl font-bold text-white">
                    {workflow.bandRoom?.roomName}
                  </h2>
                  <p className="mt-2 text-sm text-slate-400">
                    Room ID: {workflow.bandRoom?.roomId}
                  </p>
                </div>

                <div className="flex flex-wrap gap-2">
                  <StatusPill className="border-cyan-400/30 bg-cyan-500/15 text-cyan-200">
                    {workflow.bandRoom?.mode} mode
                  </StatusPill>
                  <StatusPill className="border-green-400/30 bg-green-500/15 text-green-200">
                    {workflow.status}
                  </StatusPill>
                </div>
              </div>

              <div className="mt-5 rounded-2xl border border-slate-800 bg-slate-950/60 p-4">
                <p className="text-sm font-semibold text-slate-400">
                  Workflow ID
                </p>
                <p className="mt-1 font-mono text-sm text-cyan-200">
                  {workflow.workflowId}
                </p>
              </div>
            </section>

            <section>
              <div className="mb-4">
                <p className="text-sm font-semibold uppercase tracking-[0.25em] text-slate-400">
                  Agent Outputs
                </p>
                <h2 className="mt-2 text-2xl font-bold text-white">
                  Multi-Agent Delivery Flow
                </h2>
              </div>

              <div className="space-y-5">
                {workflow.agents?.map((agent, index) => (
                  <AgentCard key={`${agent.agent}-${index}`} agent={agent} index={index} />
                ))}
              </div>
            </section>

            <section className="rounded-[2rem] border border-slate-800 bg-slate-950/70 p-6 shadow-xl shadow-black/20 backdrop-blur md:p-8">
              <div className="mb-6">
                <p className="text-sm font-semibold uppercase tracking-[0.25em] text-slate-400">
                  Band Message Timeline
                </p>
                <h2 className="mt-2 text-2xl font-bold text-white">
                  Visible Agent-to-Agent Collaboration
                </h2>
              </div>

              <div className="ml-3 space-y-4 border-l border-slate-800 pl-5">
                {workflow.bandMessages?.map((message, index) => (
                  <BandMessageCard
                    key={message.id}
                    message={message}
                    index={index}
                  />
                ))}
              </div>
            </section>

            <FinalPackage finalPackage={workflow.finalPackage} workflow={workflow} />
          </div>
        )}
      </div>
    </main>
  );
}

export default App;
